#this is a playbook to install and coficur apache in the server
- hosts: node3
  become: true
  tasks:
          - name: Install httpd
            yum:
                    name: httpd
                    state: present

          - name: Start httpd
            service:
                    name: httpd
                    state: started
                    enabled: yes

          - name: Allow on FW
            firewalld:
                    service: http
                    permanent: yes
                    immediate: yes
                    state: enabled

          - name: Edit doc page
            lineinfile:
                    path: /var/www/html/index.html
                    line: "This is from my playbook"
                    create: yes
          - name: Test the web
            shell: curl localhost

